### ISSUE TITLE
Handling of PCI address configuration not robust

### ISSUE THREAD

**Issue by robers97** [cornelisnetworks/opa-hfi1#1]
Driver fails to build on ppc64le due to invalid PCI setup.

Recommend this patch to pcie.c which better aligns with linux PCI subsystem functions.

@@ -208,8 +208,10 @@
 	/*
 	 * Save BARs and command to rewrite after device reset.
 	 */
-	dd->pcibar0 = addr;
-	dd->pcibar1 = addr >> 32;
+         pci_read_config_dword(dd->pcidev, PCI_BASE_ADDRESS_0, &dd->pcibar0);
+         pci_read_config_dword(dd->pcidev, PCI_BASE_ADDRESS_1, &dd->pcibar1);
+/*      dd->pcibar0 = addr;
+ *      dd->pcibar1 = addr >> 32;*/
 	pci_read_config_dword(dd->pcidev, PCI_ROM_ADDRESS, &dd->pci_rom);
 	pci_read_config_word(dd->pcidev, PCI_COMMAND, &dd->pci_command);
 	pcie_capability_read_word(dd->pcidev, PCI_EXP_DEVCTL, &dd->pcie_devctl);

[opa-hfi1-pcie.txt](https://github.com/01org/opa-hfi1/files/981711/opa-hfi1-pcie.txt)

**Comment by mmarcini** [comment]
The pcie issue appears to be fix in upstream source

**Comment by mmarcini** [comment]
It looks like Steven fixed this upstream:
commit e4785b0633574a607daaa04bf2fe43550055194f
Author: Steven L. Roberts <robers97@gmail.com>
Date:   Wed May 10 14:58:13 2017 -0500

    RDMA/hfi1: change PCI bar addr assignments to Linux API functions

    The Omni-Path adapter driver fails to load on the ppc64le platform
    due to invalid PCI setup.

    This patch makes the PCI configuration more robust and will
    fix 64 bit addressing for ppc64le.

    Signed-off-by: Steven L Roberts <robers97@gmail.com>
    Acked-by: Dennis Dalessandro <dennis.dalessandro@intel.com>
    Signed-off-by: Doug Ledford <dledford@redhat.com>

diff --git a/drivers/infiniband/hw/hfi1/pcie.c b/drivers/infiniband/hw/hfi1/pcie.c
index 93faf86..6a9f6f9 100644
--- a/drivers/infiniband/hw/hfi1/pcie.c
+++ b/drivers/infiniband/hw/hfi1/pcie.c
@@ -207,8 +207,8 @@ int hfi1_pcie_ddinit(struct hfi1_devdata *dd, struct pci_dev *pdev)
        /*
         * Save BARs and command to rewrite after device reset.
         */
-       dd->pcibar0 = addr;
-       dd->pcibar1 = addr >> 32;
+       pci_read_config_dword(dd->pcidev, PCI_BASE_ADDRESS_0, &dd->pcibar0);
+       pci_read_config_dword(dd->pcidev, PCI_BASE_ADDRESS_1, &dd->pcibar1);
        pci_read_config_dword(dd->pcidev, PCI_ROM_ADDRESS, &dd->pci_rom);
        pci_read_config_word(dd->pcidev, PCI_COMMAND, &dd->pci_command);
        pcie_capability_read_word(dd->pcidev, PCI_EXP_DEVCTL, &dd->pcie_devctl);

**Comment by mmarcini** [comment]
closing issue
