### ISSUE TITLE
CUDA 9.2, 10, 10.1?

### ISSUE THREAD

**Issue by paboyle** [cornelisnetworks/opa-hfi1#2]
Hello,
are these more recent versions of CUDA supported?
If so, which branches or versions should be installed?
Many thanks,

**Comment by JFleck** [comment]
For the opa-10_9 branch, we support the following combination
RHEL7.5, 7.6, SLES 15 – CUDA 10.0
SLES12.3 - CUDA 9.2

**Comment by ddalessa** [comment]
Old comment from when we were still part of Intel. Distros have moved on and so has CUDA. See Cornelisnetworks.com for our official release and documentation which will explain what CUDA versions are supported.
